id: P010347
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:45:14.580355
source_metadata:
  id: bdr:W1KG8299
  title: རྣམ་པར་རྒྱལ་བའི་རྔ་སྒྲ།
  author: ''
  volumes:
    ee277e2a682342b6a451064eb9387cf0:
      image_group_id: I1KG8489
      title: ''
      volume_number: 1
      total_pages: 154
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
