id: I1B7B23AB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T00:25:59+00:00'
last_modified: '2022-06-08T12:55:37.380232+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8299
  title: རྣམ་པར་རྒྱལ་བའི་རྔ་སྒྲ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4078':
      image_group_id: I1KG8489
      title: ''
      total_pages: 154
      order: 1
      base_file: 4078.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
